In [2]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt


training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

100.0%
100.0%
100.0%
100.0%


# Tensors

Similar to numpy arrays and matrices
- encode inputs and outputs of model
- encode model parameters

In [3]:
import torch
import numpy as np

In [4]:
#can be created directly from data or converted from numpy array
data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)
print(x_data)

x_data = torch.from_numpy(np.array(data))
print(x_data)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [7]:
# tensors keep propoerties of orig data unless overriden
x_rand = torch.rand_like(x_data, dtype = torch.float32)
print(x_rand)

tensor([[0.3151, 0.6393],
        [0.4965, 0.9345]])


In [11]:
#can use `shape` to determine shape of resulting tensor
shape = (2, 3, )
rand_tensor = torch.rand(shape)
print(rand_tensor)

tensor([[0.6666, 0.1492, 0.6855],
        [0.0447, 0.1283, 0.3901]])


In [12]:
#tensor has 3 main attributes, shape, dtype and device on which they are stored
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
#need to explicity move a tensor to an accelerator if they are available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
tensor.device

device(type='cuda', index=0)

In [16]:
#tensor handling is the same as numpy arrays
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
#torch.cat can be used to join tensors along a given dimension
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [21]:
#can also perform arithmetic on tensors
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print('y1')
print(y1)
print('y2')
print(y2)
print('y3')
print(y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print('z1')
print(z1)
print('z2')
print(z2)
print('z3')
print(z3)


y1
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
#this allows you to convert a single element tensor to. a python integer
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [24]:
#all in place operations denoted by _ suffix
tensor.add_(5)
print(tensor)
tensor.t_()
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])
tensor([[11., 11., 11., 11.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])


In [ ]:
# Bridging with numpy
#CPU tensors can share location